### ISSUE TITLE
Create use cases

### ISSUE THREAD

**Issue by K-shamG** [sysc4806/SYSC4806-WDWH#10]
- we need to define some use cases/features that we want to have
- need to organize it into which will be completed in each sprint so we have an overall plan

**Comment by andrewdlqnguyen** [comment]
Goal: Track, edit, update the LO system for all the programs in the department.

User should be able to list:
- Given year
- Given program
- All learning outcomes
- All categories
- All LO in given category
- All courses in given category
- All LO in given course
- export any of the results as CSV (comma-separated) file
- admin edit everything (exception of some limited list)

**Comment by RyanWork** [comment]
I like the suggestions. Can we make this into an actual use case diagram?

**Comment by adamstaples** [comment]
Hey folks, here is the UCM:
Let me know what you think.
Some reasons why I did things:

- the "Edit Database" I guess should include things like "edit", "add" and "remove". To make htings more readable I just left those all under "Update" implying all of the above are possible.
- I was a little iffy about the <<include>> relationships and if they are even necessary. I like having them there though so it shows that we are using all of the important variables that are mentioned in the project description. But let me know if you think there is a better way to show that. 

![ucm1](https://user-images.githubusercontent.com/22298382/53840934-7ba46c80-3f69-11e9-8a90-2c5b2afb8fb0.png)

**Comment by K-shamG** [comment]
I'm fine with the UCM. All the features are there for what we are aiming for. Since this diagram was more to organize what features we needed, I think this issue can be closed.
