### ISSUE TITLE
Deploy on Heroku

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#2]

**Comment by K-shamG** [comment]
Should we make a generic email for this project so we can all access the Heroku account?

**Comment by RyanWork** [comment]
We could create a team? It doesn't cost anything extra as long as their are <= 5 people on it (enough for our team). Do you know if there are any additional costs that can be incurred from Heroku?

**Comment by K-shamG** [comment]
I'm using heroku for my fourth year, and there are no extra costs unless you want special add-ons so we are probably safe.

**Comment by RyanWork** [comment]
> Free dynos, which are available for personal apps, are not available to Teams.

Yikes, looks like we will make a universal account. We can't use free dynos if we have teams. I'll DM you guys the credentials

**Comment by RyanWork** [comment]
Woops, closed it by accident.

I created an account and linked the repository. The next step is actually hosting something on Heroku and praying that it works :p

**Comment by RyanWork** [comment]
Closed: It works, go login to Heroku and openapp and it should be there :)
