### ISSUE TITLE
Admin Rights

### ISSUE THREAD

**Issue by K-shamG** [sysc4806/SYSC4806-WDWH#21]
An admin should be able to edit the category field upon login

**Comment by andrewdlqnguyen** [comment]
For this admin rights:
After admin logs in by pressing the top right and inputting their authentications, do we want an edit icon to appear on the other pages after submit?

ex/
Issue #30 will have login and password and after submit, it redirect back to the main page  with additional option to edit(icon) ya?

**Comment by K-shamG** [comment]
I agree with the login and then redirect to main page for editing. As far as I understood, an admin should be able to add or remove categories and learning outcomes and assign those to courses/programs etc. In my mind, I'm picturing that an admin would login, see the main page and have an added dashboard page where they could see all the categories/learning outcomes and map them in that view. It could be in the same main page, but I feel like that could get a little confusing.
