### ISSUE TITLE
Format Readme File

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#3]
They will be looking through the readme file, someone should format and put stuff in it.

**Comment by RyanWork** [comment]
The README.md file on Github should summarize the current state of the project as per the Kanban, and include a plan for the next sprint. It should also include the up-to-date schema of the database.

**Comment by K-shamG** [comment]
I put a table for our Kanban current state using this: https://www.tablesgenerator.com/markdown_tables
