### ISSUE TITLE
Create DB Image from IntelliJ (ER diagram)

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#32]
Title. We will need to wait for #18 before IntelliJ will create anything I believe.

**Comment by K-shamG** [comment]
Instructions to generate (should be done before each iteration):

1. View->Tool Windows->Persistance
2. Right Click entityManagerFactory and click ER Diagram

![image](https://user-images.githubusercontent.com/15951317/53817855-a58f6c00-3f34-11e9-9e51-c5a40b7076e4.png)
