### ISSUE TITLE
Model Validation

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#35]
We should probably annotate some of our model properties to validate the parameters. Things like `year` for example probably should never be anything less than 1900 for example.

We might need a discussion on what kinds of things we want to validate and what the parameters might be.

**Comment by andrewdlqnguyen** [comment]
For the years i was thinking a backtrack of 5 years. So for 2019, it'll pull back to when we first started in 2014.

Kinda like how Carleton updated their program tree.
https://carleton.ca/engineering-design/current-students/undergrad-academic-support/prerequisites/

In the description:
"A course belongs to one or many programs, and a program has many courses (in a given year). A course is taught in a given "year" (1st, 2nd etc., not school year)"

I think we only want info for year 1-4 for the chosen program? It also says info can change year by year so maybe we want two separate year? Year 1-5 courses the program offers, and the year the user enrolled in the program.

Im not sure..

**Comment by RyanWork** [comment]
I questioned the same thing. I wasn't really sure if it was saying like school year is denoted by 1st, 2nd, 3rd, 4th and henceforth, should not be the year. I think it really is kind of confusing the way they worded it and we can ask the TA on Wednesday. 

If that is the case, we can just limit the range on year from 1-4 then??

**Comment by K-shamG** [comment]
It's supposed to be 1-4. Think of it like the engineering progression trees and how they map that out. That is how I imagine it.

**Comment by SupriyaGadigone** [comment]
Just starting this discussion up again

Category:
- Name: Cannot be null or ""
- Learning Outcomes: It's okay for this to be empty?

Course:
- Year: Range would be from Todays year to back to 4 years
- Name: Cannot be null or ""
- Code: Cannot be null or ""

Learning outcomes:
- Name: Cannot be null or ""
- Category: Can be null or empty I think cause a learning outcome can be not assigned yet
- Courses: Can be null or empty I think cause a course can be not assigned yet 

Program:
- Name: Cannot be null or ""
- Course: Cannot be null or empty

**Comment by K-shamG** [comment]
Category
* LO not assigned til later, can be empty

Course
* Year: Would not be "today's year", but as we discussed in prior comments, it should be 1-4

LO 
* I don't think category should be null -> its two constructor args are name and category

Program 
* Course is no longer an arg in it's constructor so it can be empty at start and added later
