### ISSUE TITLE
March 6 (Wednesday) Demo

### ISSUE THREAD

**Issue by SupriyaGadigone** [sysc4806/SYSC4806-WDWH#39]
I am not sure if we need to have anything formal but it will be nice to have some organization for the 15 minute demo.

The requirements for this demo states that:
1. Should collect data from the back end, do something with it and display the result. 
2. There should be a GitHub repo, integrated with Travis CI (or other hosted CI), and the app should be up and running on Heroku.
3.  Inspect the README file, the Issues, the Kanban, the code reviews, the tests, and we will verify that everybody is participating in all aspects of the project.

I was thinking of the demo going this way:
1. Show the UI and the data in it 
2. Show the issues, commits, README...
3. Each person then just goes around saying what they did maybe? not sure

Kay yeah for sure going to need help to organize this in a better way

**Comment by andrewdlqnguyen** [comment]
They'll probably have a guideline something similar to 3303 and what you listed.
Milestone 1 and 2 are presented to the TA, i'm sure it won't be really strict.
