### ISSUE TITLE
.gitignore Target and Other Compiled Stuff

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#48]
I think we need to change our .gitignore. Our .gitignore is sufficient for just using the IntelliJ IDE. However, you may notice the "target/" folder has changes every time you commit, but never actually changed anything in there!

The "target/" folder is compiled data from Maven. I believe the general rule of thumb is that we should not be committing any compiled files/binaries to the repository. I think having this change would de-clutter our commits and make code reviews a little bit easier to sift through without all these target folder changes.

Here's the .gitignore of the first link of Google for spring-boot https://github.com/spring-projects/spring-boot/blob/master/.gitignore

**Comment by andrewdlqnguyen** [comment]
Yeaa this was the problem i was getting. The target folder keeps on changing after push. and when pulled from remote, i sometime got errors which made me confused cuz i was not aware of making any changes to them.

like few changes i noticed were some silly refactors on class/method names (ex getListRepository turned into GetListRepository)

**Comment by RyanWork** [comment]
See #53
