### ISSUE TITLE
Build Database Schema

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#5]
Professor Esfandiari mentioned we can create a database schema directly from IntelliJ.

**Comment by K-shamG** [comment]
![52002719_348923782618666_7516838563577593856_n](https://user-images.githubusercontent.com/15951317/52739086-24306380-2f9e-11e9-9fe6-6d671d44adc4.jpg)

**Comment by RyanWork** [comment]
I think it seems okay for the most part. Can you elaborate on the Category/Course relationship table? From my interpretation, there should be a relationship between Category/Learning Outcomes instead. Based on the description:

> Each learning objective belongs to a Category. There's a limited list of Categories which can be edited by the Administrator (such as "Design", "Communication Skills").

This was my interpretation of the model relationships.

![image](https://user-images.githubusercontent.com/15223407/52750855-5c926a80-2fbb-11e9-9f52-83b4fa840bac.png)

_**EDIT:** Seeing Kshamina's diagram made me realize I missed a * multiplicity between course and learning outcomes._

**Comment by K-shamG** [comment]
This also makes sense. How I saw it was since it says show "all the learning outcomes within a given category, all the courses covering a given category", I assumed it meant we can grab all the categories associated with a course and since it's a 1-to-many for LO and category, you could then grab the LO's that fall under this category. 

BUT I think your way makes more sense. So, it will be a Course-LO table and then I think everything else is the same (minus the CourseCategory table) :O

**Comment by K-shamG** [comment]
![db schema v1](https://user-images.githubusercontent.com/15951317/52798210-77112600-3045-11e9-8775-ff8fa824d85e.png)

**Comment by K-shamG** [comment]
^I was looking into JPA db stuff like we did in class, and I dont think we need the subtables (ProgramCourses and CourseLO's) because we just use the @ManyToMany

**Comment by RyanWork** [comment]
I believe the annotations provided by JPA is an abstraction of the ORM process. I think that behind the scenes JPA is still building the relationships between the @ManyToMany relation. I suppose IntelliJ will tell us, but for now I think this is okay. 

This will give us a lead on the type of models we need to define. From there we can finish up Issue #9 .

**Comment by andrewdlqnguyen** [comment]
Hey sorry for hopping on the project so late.
Anyways, yea the table i came up with is pretty much the same as Ryan's. 
Can't we have the course program, and LO populate all the list without CourseLearningOutcomes and ProgramCourses classes included?

**Comment by RyanWork** [comment]
In the ORM process we build relationship tables when there is a many-to-many relationship. It's just how the mapping works so we minimize the amount of redundancy in our databases. 

I think we can close this issue. Our database seems okay. We can reopen it if we later feel that we need to edit it. For the most part, it should be good enough to start using. The schema will probably change once we start implementing logins.
