### ISSUE TITLE
Select for Years

### ISSUE THREAD

**Issue by K-shamG** [sysc4806/SYSC4806-WDWH#56]
- Right now it is hardcoded to 1 - 5

Possible Options
- change options available based on onchange of program
- populate with years available from any course
- remain hardcoded but done with enums

**Comment by andrewdlqnguyen** [comment]
i vote for enums.
could just pass an equal comparison when the years are clicked to check course year.

**Comment by RyanWork** [comment]
> change options available based on onchange of program

Can you elaborate on this? Like the select would populate the list based on the range of years that the courses are offered in?

I think it's better for it to be dynamic. Some courses, like a master's program, wouldn't have any courses for its 3rd and 4th year; if it were a two year master's program for example. From a basic perspective, I think just having it hard coded with enums is okay, but we may look into making it dynamic before the final iteration.

**Comment by K-shamG** [comment]
> > change options available based on onchange of program
> 
> Can you elaborate on this? Like the select would populate the list based on the range of years that the courses are offered in?
> 

Yes, exactly. The select would populate when it changed values.
