### ISSUE TITLE
How to populate data?

### ISSUE THREAD

**Issue by K-shamG** [sysc4806/SYSC4806-WDWH#57]
Right now it is done with Application command line runner. 
Do we want to convert this to data.sql or postgreSQL? What is everyone's opinion on this one?

**Comment by andrewdlqnguyen** [comment]
i thought data.sql would be the easiest but i couldnt get it to work when i tried. something to do with setting up the database source n having user/pass authentication. 

I wouldnt mind postgres since there's steps to do it from Babak.

**Comment by K-shamG** [comment]
@andrewdlqnguyen did you try data.sql before or after I fixed the mappings?

**Comment by andrewdlqnguyen** [comment]
oh....before. LOL
That maybe why.. :D

**Comment by RyanWork** [comment]
I'm okay with the data.sql. But if you want to take the opportunity to learn and do Postgres I'm not opposed to it. Idk what the details are behind it though, is it a lot of work?

**Comment by K-shamG** [comment]
Idk either. I start with data.sql and we can convert to postgreSQL for final iteration/if there is time
