### ISSUE TITLE
Edit Interface Suggestions.

### ISSUE THREAD

**Issue by andrewdlqnguyen** [sysc4806/SYSC4806-WDWH#59]
Refer to #21
How do we want the interface to look when admin is logged in?

This is what i was thinking it might happen:
phase 1: user logs in
phase 2: backend verifies account, if true then interface will look like this. You see an edit option top right
![step1](https://user-images.githubusercontent.com/25157934/54103971-b3197b80-43a4-11e9-8426-bebd6a39ed73.PNG)
phase 3: when pressed, screen fades and modal opens up.
![step2](https://user-images.githubusercontent.com/25157934/54104023-dba17580-43a4-11e9-85cf-7bf290ebbb2c.PNG)
Sorry instead of Edit and Apply, it should be Edit and Add.
Edit will be blurred out till a data is pressed in the list. When edit is eligible to be pressed, the user can modify the existing values for that data and or remove. A new modal will appear to direct user the options
When add is pressed, a diff modal will appear to add new data types.

any suggestions?

**Comment by K-shamG** [comment]
I like the way you are using the modal to edit or add a new in the same box. But how will you edit/add a program from this same box? Also, I find the edit in the top right corner not very intuitive. If I were using this, I would not really know what I was about to edit by clicking this button since it is not located beside a program or course etc. This was one of the reasons I was hesitant on having this as a single-page-application.

**Comment by andrewdlqnguyen** [comment]
ya i agree with you, that was something i was iffy about too but placing the edit beside each of them would look cluttered. hmm
Would it prob be better to differentiate from the two by providing a second page for admins then? I wanted to try n stick with SPA.

If we stick with SPA then i think the modal will prob have to break down in more steps to understand what Edit really does. 
OR
Another box appears just below the nav bar thats treated like an Edit Tool Bar
Hover over gives info: Admin privilege - Tool bar that allows you to add/remove/edit the data
Box with 3(add/remove/edit) icon when pressed opens up what you want to modify (program,course,outcome,code,etc).

**Comment by K-shamG** [comment]
Yeah I would like to keep it SPA as well. The second navbar could be cool. 
Another option is having the second nav bar for add/delete and an edit on the table row. The admins table would show program, course, category and LO (more than what a regular user sees) and then there is an edit button for the row. 

![image](https://user-images.githubusercontent.com/15951317/54141308-c99ef180-43fb-11e9-856f-eaf5ea484721.png)

When that edit is clicked, a modal could open with prepopulated data for that program, the courses offered. If a course attributes are to be editted from here, it could be expanded using bootstrap collapse: https://getbootstrap.com/docs/4.1/components/collapse/ 

Idk if that modal would be too complicated, would love some other input @adamstaples @RyanWork @SupriyaGadigone

**Comment by andrewdlqnguyen** [comment]
Hmm I liked that second idea! "show program, course, category and LO (more than what a regular user sees) and then there is an edit button for the row.

I looked more into doing something like this but i couldnt wrap my head around seeing it work.

But i also got another idea
How does this sound:
Something similar to your #63 issue with the sorting but for admin view. 

-A master table will appear with all topics showing in each column per row
-an add button, a filter button and populate button on right side to give admin action options.

Add Button: simply adds new data

Filter button: shoots out a modal that displays different ways to filter the data to get what the admin specifically want. Presses okay and brings back to the master table view. (Maybe a counter on the side that'll display to give awareness how many data will appear if they press populate)

Populate button: Displays all the data (populates the master table) depending on the filter and an edit button will appear on the side of those data rows.

I think this way if an admin goes in blind, they can find what they want to edit in general.

**Comment by K-shamG** [comment]
I think the add in a the master table columns is a good idea! Very intuitive for the admin. Also yes to the filtering - this is easier since we will already have that logic implemented as well.
