### ISSUE TITLE
Weekly scrum - March 22, 2019

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#66]
every team member should add comments with their own contribution, i.e. their answers to the questions:

what have I done this week?
what will I do next week?
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by SupriyaGadigone** [comment]
What have I done this week?

- Code Reviews #78, #68
- Finished working on CSV #16
- Finished working on Filter #19

What will I do next week?

- Work on fixing any bugs with the features I have implemented
- Model Validation #35 
- Yet to discuss the parts with the team (will update as decided)

**Comment by RyanWork** [comment]
What have I done this week?

- Independent Test Cases in #68 
- Removed the Target Folder #64 
- Helped Adam in Fixing Add feature #78 
- Reviewed #72 

What will I do next week?

- Help clean up the add feature
- Delete/Update feature?

**Comment by K-shamG** [comment]
What have I done this week?
* Reviewed #16, #51, #30 
* Helped fix build failure for admin security changes

What will I do next week?
* admin features
* test view with more data #65 
* select for years #56

**Comment by andrewdlqnguyen** [comment]
what have I done this week?
- Made the Admin Page interface #59 
- Made the login page + security #51 #21 #69
- Helped with #73 
- Reviewed #70 #63 

what will I do next week?
- Change the filter system on admin page to same one as user page
- Possibly change user/pass to avoid deprecation (encryption?) - not too important
- Looking into breaking the site and find problems.

**Comment by adamstaples** [comment]
what have I done this week?

- Reviewed login page and security #69 
- Began adding new add features. 
- Updated admin page with edit button and table similar to user page

what will I do next week?

- Finish the admin page #80 
- work on edit feature #81 

what is holding me back? (if applicable)
NA
