### ISSUE TITLE
Spring Security

### ISSUE THREAD

**Issue by andrewdlqnguyen** [sysc4806/SYSC4806-WDWH#69]
So Im working on making the Spring Security and the configuration is not made for SPA. The methods given redirects to pages depending on login output.

From online, I found that I would have to install Spring Lemon and use Handlers if we want to keep it SPA but that I'll have to look more into.

You guys cool if we use multi page? Only pages we'll prob need r just Login, Index - User View, Index - Admin View. The feel will still be like a SPA

**Comment by K-shamG** [comment]
I'm fine with multi page for the login stuff!

**Comment by RyanWork** [comment]
Yeah I think that's okay. We dont have to make the entire thing truly SPA. If anything that might be a final iteration feature. I would focus on getting it working first.
