### ISSUE TITLE
Weekly scrum – February 22, 2019

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#7]
> every team member should add comments with their own contribution, i.e. their answers to the questions:
> - what have I done this week?
> - what will I do next week?
> - what is holding me back? (if applicable)
> - Expected length: 1-2 sentences per item.

**Comment by K-shamG** [comment]
What have I done this week?
- wrote fix for Travis build issue #12 
- assisted with design of DB Schema #5 
- assisted with design of Entity classes #9
- assisted with design of basic UI #11 
- formatted README File (still in progress) #3

What will I do next week?
- continue formatting README #3 
- create basic UI #24 

What is holding me back? (if applicable)
- N/A

**Comment by SupriyaGadigone** [comment]
What have I done this week?

- Started discussions on Features/UI Breakdown #11 
- Implemented DB skeleton models #17 
- Initiated setup for repository by adding Maven and Travis integration (which had errors)

What will I do next week?

- Populate DB with Data #22 
- Create Model DB Connections #18

**Comment by RyanWork** [comment]
What have I done this week?

- Built the GitHub! Organized the Repo with the Kanban #4 
- Created the REST Repositories for our models #15 & #25 
- Setup an account for Heroku to deploy #2 
- Started the basis for our models in the UML Class Diagram #9
- Contributed to building database schema #5 
- Setup Travis CI #1 

What will I do next week?
- Finalize our model class diagram #9 
- I want to start creating some of the REST endpoints for some of our data
- Build some test cases

What is holding me back? (if applicable)
- Waiting on reviewers for #25 
- To create the endpoints for the data, I think I will need #18 to be finished

**Comment by adamstaples** [comment]
What have I done this week?
- Reviewed UML #9 
- Reviewed feature branches #6 

What will I do next week?
- Create use case diagram as in issue #10 
- Look into implementing database scheme #15 
- Move onto populating DB with data #22 
- Review issue #25

**Comment by andrewdlqnguyen** [comment]
What have I done this week?

- Reviewed and assisted Features/UI Breakdown #11 
- Reviewed UML #9 
- Looked into Create use cases #10 

What will I do next week?

- Looking into helping with test cases
- Looking into helping with UI
- Work on the Main Feature View #24 
- Work on the admin vs guest privileges #21
