### ISSUE TITLE
Cant wire Beans on Tests

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#73]
IntelliJ is angry and says it can't wire the beans for the repositories in my test cases. Despite saying this, the tests work fine. So I dont know if that's a bug on IntelliJs end because if it couldn't wire the beans then I wouldnt be able to use the repositories.

I might look into just suppressing the warnings if that's the case.

**Comment by andrewdlqnguyen** [comment]
Would this be a problem for Travis?

This is what i did to bypass it: 
https://stackoverflow.com/questions/26889970/intellij-incorrectly-saying-no-beans-of-type-found-for-autowired-repository

seems prone to future problems if it really isnt InteillJ's fault

**Comment by andrewdlqnguyen** [comment]
> Would this be a problem with Travis?
> 
> This is what i did to bypass it:
> https://stackoverflow.com/questions/26889970/intellij-incorrectly-saying-no-beans-of-type-found-for-autowired-repository
> 
> seems prone to future problems if it really isnt InteillJ's fault



> with

**Comment by andrewdlqnguyen** [comment]
oops

**Comment by RyanWork** [comment]
Based on the answer to that, it is just a an IntelliJ interpretation. This means in terms of building and compilation it doesn't actually negatively impact the program. It's just intelliJ has problems recognizing that this is valid. 

Travis is just using a build tool to run tests. It builds it and runs it, nothing more. It probably won't even notice that there is something that says "cannot wire bean". Long story short, we gucci.
