### ISSUE TITLE
Weekly scrum - March 29, 2019

### ISSUE THREAD

**Issue by SupriyaGadigone** [sysc4806/SYSC4806-WDWH#79]
every team member should add comments with their own contribution, i.e. their answers to the questions:

what have I done this week?
what will I do next week?
what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by SupriyaGadigone** [comment]
What have I done this week?

- Code Reviews #84
- Started working on Model Validation #35

What will I do next week?

- Finish up  Model Validation #35
- Anything els that needs to be done

**Comment by RyanWork** [comment]
What have I done this week?

- Reviewed #83 
- Implemented add feature #78 #80 

What will I do next week?

- Apply changes as discussed in #80

**Comment by andrewdlqnguyen** [comment]
What have I done this week?

- Reviewed #83 
- Cleaned up some of the codes for admin page
- Started working on Delete Feature #82 

What will I do next week?
- Finish Delete Feature #82 
- Look into the Filter for Admin

**Comment by K-shamG** [comment]
What have I done this week?
* #56 
* Reviewed #84 

What will I do next week?
* testing for many LO's, adjust view accordingly

**Comment by adamstaples** [comment]
what have I done this week?
Reviewed #84 
Began work  for edit #81 
Reviewed Add feature Implementation

what will I do next week?
Continuing work on #84  and #81 

what is holding me back? (if applicable)
