### ISSUE TITLE
New Filtering System for Admin Page

### ISSUE THREAD

**Issue by andrewdlqnguyen** [sysc4806/SYSC4806-WDWH#86]
I was trying to replicate the same filtering system as the index page but seems there are some more changes that needs to be made for multiple categories to appear. I dont fully understand all the connections yet so I couldnt get it to properly filter (It just replaces the admin table with the regular table which i can see that happening in HomeController and index javascipt). I could look more into this but i think someone else who made the filter would prob be able to fix it much quicker.

im going to try n work on the delete feature

**Comment by K-shamG** [comment]
IMO, filtering in admin is not really necessary because we have the search bar in the table already. opinions? @adamstaples @RyanWork @SupriyaGadigone

**Comment by RyanWork** [comment]
He already removed the filtering stuff from the addfeature branch.
