### ISSUE TITLE
Create UML Class Diagram

### ISSUE THREAD

**Issue by RyanWork** [sysc4806/SYSC4806-WDWH#9]
Should only be a class diagram of our models.

**Comment by RyanWork** [comment]
Here is my drawing of the UML Class Diagram for only the models (as specified in the required docs)
`. . . Include a UML class diagram of your Models (and only of the Models!)`

Can someone please validate the correctness of this? Thank you!

![umlclassdiagram](https://user-images.githubusercontent.com/15223407/53110180-6ca0d180-3508-11e9-900f-34837bb65326.png)

**Comment by K-shamG** [comment]
I'm not sure about the 0 on the Program side. Doesn't a program have to have courses (aka that 0 should be a 1)? 

For further filtering, we may want to add a "semester" attribute to Course (but this can be added during the second iteration). And I'm guessing we will add the methods later, once the models are developed? Otherwise, it looks good to me.

**Comment by RyanWork** [comment]
I suppose you could argue the fact that a newly introduced program may not have any set of courses yet, but the program could exist? I don't believe the relationship between the two is that strong. Maybe the others have opinions on it. Fundamentally, this is probably a design choice issue.

Looking back, I could have made the Category/LearningOutcome relationship an aggregation? What do you think? In fact, what's stopping me from making all of these aggregations :P?

**Comment by K-shamG** [comment]
Yeah, I see your point - I'm cool with 0 then. They could definitely all be notated as aggregations.

**Comment by RyanWork** [comment]
Mehh, I think they might be okay as associations looking back on it. An aggregation is more like saying something is part of something. It is composed of a set of things. All of these classes seem relatively independent. I think... I feel like it should be okay as it is then.

**Comment by K-shamG** [comment]
I agree for most of the relationships except program vs course. I think that should be an aggregation because a course belongs to a program but can exist independently without a program as well.
